# Generated by Django 5.1.4 on 2025-01-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
